# 비용 안전장치 2: 할당량(quota) 정책으로 상시 무료 범위를 넘는 자원은 생성 자체를 거부한다
# 예산(budget.tf)은 과금 후 알림이고, 할당량은 콘솔·API·Terraform 어디서 만들든 생성 요청 단계에서 막는다
# 같은 자원을 대상으로 한 문장은 뒤의 것이 앞의 것을 덮어쓰므로 "전부 0 → 무료분만 허용" 순서로 쓴다
# 기존 자원에는 영향이 없고, 이미 쓰는 양(1 OCPU / 6GB / 부트 50GB)은 한도 안이다
# 데이터 전송량(월 10TB 무료)처럼 할당량 대상이 아닌 과금은 예산 알림으로만 잡힌다
resource "oci_limits_quota" "free_tier" {
  compartment_id = var.tenancy_ocid # 할당량 정책은 루트 compartment에 만든다
  name           = "mini-mes-free-tier"
  description    = "mini-mes: 상시 무료 범위를 넘는 자원 생성 차단"
  statements = [
    # VM: A1만 2 OCPU / 12GB까지 (GPU·x86 등 나머지 유료 shape는 0)
    "zero compute-core quotas in tenancy",
    "set compute-core quota standard-a1-core-count to 2 in tenancy",
    "zero compute-memory quotas in tenancy",
    "set compute-memory quota standard-a1-memory-count to 12 in tenancy",
    "zero compute quotas in tenancy", # 구형 shape 단위 할당량
    # 블록·부트 볼륨 합계 200GB, 백업 5개 (상시 무료 범위)
    "set block-storage quota total-storage-gb to 200 in tenancy",
    "set block-storage quota backup-count to 5 in tenancy",
    # 쓰지 않는 유료(또는 무료분을 넘으면 과금되는) 서비스는 전부 0
    # 그대로 두는 것: vcn·vcnip(현재 네트워크), 계정 관리(identity·compartments·limits·regions·tagging 등),
    # 무료인 관리 기능(monitoring·logging·notifications·events·cloud-shell·certificates·cost-management)
    "zero load-balancer quotas in tenancy",
    "zero network-load-balancer-api quotas in tenancy",
    "zero database quotas in tenancy",
    "zero postgresql quotas in tenancy",
    "zero nosql quotas in tenancy",
    "zero redis quotas in tenancy",
    "zero open-search quotas in tenancy",
    "zero goldengate quotas in tenancy",
    "zero database-migration quotas in tenancy",
    "zero dbtools quotas in tenancy",
    "zero autonomous-recovery-service quotas in tenancy",
    "zero exadata-fleet-update quotas in tenancy",
    "zero compute-management quotas in tenancy",
    "zero container-engine quotas in tenancy",
    "zero batch-computing quotas in tenancy",
    "zero faas quotas in tenancy",
    "zero api-gateway quotas in tenancy",
    "zero filesystem quotas in tenancy",
    "zero filestoragenetapp quotas in tenancy",
    "zero lustrefilestorage quotas in tenancy",
    "zero rndrive quotas in tenancy",
    "zero object-storage quotas in tenancy",
    "zero data-transfer quotas in tenancy",
    "zero fast-connect quotas in tenancy",
    "zero vpn quotas in tenancy",
    "zero network-firewall quotas in tenancy",
    "zero global-accelerator quotas in tenancy",
    "zero waf quotas in tenancy",
    "zero waas quotas in tenancy",
    "zero waa quotas in tenancy",
    "zero dns quotas in tenancy",
    "zero email-delivery quotas in tenancy",
    "zero kms quotas in tenancy",
    "zero streaming quotas in tenancy",
    "zero oci-kafka quotas in tenancy",
    "zero queue quotas in tenancy",
    "zero analytics quotas in tenancy",
    "zero big-data quotas in tenancy",
    "zero data-flow quotas in tenancy",
    "zero data-integration quotas in tenancy",
    "zero data-catalog quotas in tenancy",
    "zero data-science quotas in tenancy",
    "zero data-labeling quotas in tenancy",
    "zero datalake quotas in tenancy",
    "zero ai-speech quotas in tenancy",
    "zero ai-vision quotas in tenancy",
    "zero generative-ai-agent quotas in tenancy",
    "zero digital-assistant quotas in tenancy",
    "zero digital-media quotas in tenancy",
    "zero integration quotas in tenancy",
    "zero process-automation quotas in tenancy",
    "zero blockchain quotas in tenancy",
    "zero devops quotas in tenancy",
    "zero apm quotas in tenancy",
    "zero operations-insights quotas in tenancy",
    "zero stack-monitoring quotas in tenancy",
    "zero java-management quotas in tenancy",
    "zero osmh quotas in tenancy",
    "zero disaster-recovery quotas in tenancy",
    "zero ocvp quotas in tenancy",
    "zero ccatc quotas in tenancy",
    "zero cloud-bridge quotas in tenancy",
    "zero ocm-migration quotas in tenancy",
    "zero multicloud quotas in tenancy",
    "zero secure-desktops quotas in tenancy",
    "zero iot quotas in tenancy",
  ]
}
