services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mini_mes
      POSTGRES_USER: mes_user
      POSTGRES_PASSWORD: mes_password
    ports:
      - "5432:5432"
    volumes:
      - mes_pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mes_user -d mini_mes"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
    environment:
      DATABASE_URL: postgresql://mes_user:mes_password@db:5432/mini_mes
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:v2.55.1
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:11.3.0
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  mes_pgdata:
