apiVersion: v1
kind: Service
metadata:
  name: {{ include "mini-mes.fullname" . }}-api
  labels:
    {{- include "mini-mes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "mini-mes.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.port }}
