apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mini-mes.fullname" . }}-db-data
  labels:
    {{- include "mini-mes.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.storage }}
