apiVersion: v1
kind: Service
metadata:
  name: {{ include "mini-mes.fullname" . }}-db
  labels:
    {{- include "mini-mes.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mini-mes.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: db
  ports:
    - port: {{ .Values.db.port }}
      targetPort: 5432
