apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mini-mes.fullname" . }}-db
  labels:
    {{- include "mini-mes.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.password | quote }}
  POSTGRES_DB: {{ .Values.db.database | quote }}
  DATABASE_URL: "postgresql://{{ .Values.db.user }}:{{ .Values.db.password }}@{{ include "mini-mes.fullname" . }}-db:{{ .Values.db.port }}/{{ .Values.db.database }}"
